name: CI Pipeline2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13' # spécifiez la version de Python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # assurez-vous d'avoir ce fichier
      - name: Run tests
        run: |
          pytest # ou toute autre commande pour exécuter vos tests

      - name: Build Docker Image
        run: docker build -t flask-app:latest .

      - name: Run FlaskApp
        run: |
          docker run flask-app:latest

      - name: Push Docker Image to Docker Hub
        if: success()  # Condition pour n’exécuter cette étape que si les tests réussissent
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push my-image:latest
